-- =============================================================
-- Criação das tabelas eSocial para Informe de Rendimento
-- Executar em: folha_flavio, folha_kiko, folha_beatriz
-- (folha_agronil já possui todas as tabelas)
--
-- Use IF NOT EXISTS — seguro rodar mesmo se já existirem.
-- =============================================================

-- ---------------------------------------------------------------
-- BANCO folha_flavio
-- ---------------------------------------------------------------
USE folha_flavio;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_CONFIG')
CREATE TABLE ESOCIAL_CONFIG (
    CHAVE   VARCHAR(50)  NOT NULL PRIMARY KEY,
    VALOR   VARCHAR(500) NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210')
CREATE TABLE ESOCIAL_S1210 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210_DETALHE')
CREATE TABLE ESOCIAL_S1210_DETALHE (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    PER_REF       VARCHAR(10)   NULL,
    IDE_DMDEV     VARCHAR(40)   NULL,
    TP_PGTO       VARCHAR(10)   NULL,
    VR_LIQ        DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    ARQUIVO       VARCHAR(260)  NOT NULL,
    TIPO_XML      VARCHAR(30)   NOT NULL,
    NR_RECIBO     VARCHAR(80)   NULL,
    NR_REC_ARQ    VARCHAR(80)   NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210_COMPL')
CREATE TABLE ESOCIAL_S1210_COMPL (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    ARQUIVO       VARCHAR(260)  NOT NULL,
    ORIGEM        VARCHAR(10)   NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_INFORME_AJUSTE_MANUAL')
CREATE TABLE ESOCIAL_INFORME_AJUSTE_MANUAL (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       INT           NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NOT NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    OBS           VARCHAR(300)  NULL,
    CRIADO_EM     DATETIME      NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_NOME_OVERRIDE')
CREATE TABLE ESOCIAL_NOME_OVERRIDE (
    CPF           CHAR(11)      NOT NULL PRIMARY KEY,
    NOME          VARCHAR(200)  NOT NULL,
    OBS           VARCHAR(300)  NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5001')
CREATE TABLE ESOCIAL_S5001 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_CP_SEG     DECIMAL(18,2) NOT NULL DEFAULT 0,
    VR_DESC_SEG   DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5002')
CREATE TABLE ESOCIAL_S5002 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VLR_BASE_IRRF DECIMAL(18,2) NOT NULL DEFAULT 0,
    VLR_IRRF      DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5003')
CREATE TABLE ESOCIAL_S5003 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_FGTS       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5011')
CREATE TABLE ESOCIAL_S5011 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_CP_APUR    DECIMAL(18,2) NOT NULL DEFAULT 0,
    VR_IRRF       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

PRINT 'folha_flavio: OK';
GO

SELECT name AS tabela_criada FROM sys.tables WHERE name LIKE 'ESOCIAL%' ORDER BY name;
GO


-- ---------------------------------------------------------------
-- BANCO folha_kiko
-- ---------------------------------------------------------------
USE folha_kiko;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_CONFIG')
CREATE TABLE ESOCIAL_CONFIG (
    CHAVE   VARCHAR(50)  NOT NULL PRIMARY KEY,
    VALOR   VARCHAR(500) NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210')
CREATE TABLE ESOCIAL_S1210 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210_DETALHE')
CREATE TABLE ESOCIAL_S1210_DETALHE (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    PER_REF       VARCHAR(10)   NULL,
    IDE_DMDEV     VARCHAR(40)   NULL,
    TP_PGTO       VARCHAR(10)   NULL,
    VR_LIQ        DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    ARQUIVO       VARCHAR(260)  NOT NULL,
    TIPO_XML      VARCHAR(30)   NOT NULL,
    NR_RECIBO     VARCHAR(80)   NULL,
    NR_REC_ARQ    VARCHAR(80)   NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210_COMPL')
CREATE TABLE ESOCIAL_S1210_COMPL (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    ARQUIVO       VARCHAR(260)  NOT NULL,
    ORIGEM        VARCHAR(10)   NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_INFORME_AJUSTE_MANUAL')
CREATE TABLE ESOCIAL_INFORME_AJUSTE_MANUAL (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       INT           NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NOT NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    OBS           VARCHAR(300)  NULL,
    CRIADO_EM     DATETIME      NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_NOME_OVERRIDE')
CREATE TABLE ESOCIAL_NOME_OVERRIDE (
    CPF           CHAR(11)      NOT NULL PRIMARY KEY,
    NOME          VARCHAR(200)  NOT NULL,
    OBS           VARCHAR(300)  NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5001')
CREATE TABLE ESOCIAL_S5001 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_CP_SEG     DECIMAL(18,2) NOT NULL DEFAULT 0,
    VR_DESC_SEG   DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5002')
CREATE TABLE ESOCIAL_S5002 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VLR_BASE_IRRF DECIMAL(18,2) NOT NULL DEFAULT 0,
    VLR_IRRF      DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5003')
CREATE TABLE ESOCIAL_S5003 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_FGTS       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5011')
CREATE TABLE ESOCIAL_S5011 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_CP_APUR    DECIMAL(18,2) NOT NULL DEFAULT 0,
    VR_IRRF       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

PRINT 'folha_kiko: OK';
GO

SELECT name AS tabela_criada FROM sys.tables WHERE name LIKE 'ESOCIAL%' ORDER BY name;
GO


-- ---------------------------------------------------------------
-- BANCO folha_beatriz
-- ---------------------------------------------------------------
USE folha_beatriz;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_CONFIG')
CREATE TABLE ESOCIAL_CONFIG (
    CHAVE   VARCHAR(50)  NOT NULL PRIMARY KEY,
    VALOR   VARCHAR(500) NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210')
CREATE TABLE ESOCIAL_S1210 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210_DETALHE')
CREATE TABLE ESOCIAL_S1210_DETALHE (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    PER_REF       VARCHAR(10)   NULL,
    IDE_DMDEV     VARCHAR(40)   NULL,
    TP_PGTO       VARCHAR(10)   NULL,
    VR_LIQ        DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    ARQUIVO       VARCHAR(260)  NOT NULL,
    TIPO_XML      VARCHAR(30)   NOT NULL,
    NR_RECIBO     VARCHAR(80)   NULL,
    NR_REC_ARQ    VARCHAR(80)   NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S1210_COMPL')
CREATE TABLE ESOCIAL_S1210_COMPL (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    ARQUIVO       VARCHAR(260)  NOT NULL,
    ORIGEM        VARCHAR(10)   NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_INFORME_AJUSTE_MANUAL')
CREATE TABLE ESOCIAL_INFORME_AJUSTE_MANUAL (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       INT           NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    DT_PAGTO      VARCHAR(20)   NOT NULL,
    REND_TRIB     DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS          DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF          DECIMAL(18,2) NOT NULL DEFAULT 0,
    REND_TRIB_13  DECIMAL(18,2) NOT NULL DEFAULT 0,
    INSS_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    IRRF_13       DECIMAL(18,2) NOT NULL DEFAULT 0,
    COD_RECEITA   VARCHAR(20)   NULL,
    OBS           VARCHAR(300)  NULL,
    CRIADO_EM     DATETIME      NOT NULL DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_NOME_OVERRIDE')
CREATE TABLE ESOCIAL_NOME_OVERRIDE (
    CPF           CHAR(11)      NOT NULL PRIMARY KEY,
    NOME          VARCHAR(200)  NOT NULL,
    OBS           VARCHAR(300)  NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5001')
CREATE TABLE ESOCIAL_S5001 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_CP_SEG     DECIMAL(18,2) NOT NULL DEFAULT 0,
    VR_DESC_SEG   DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5002')
CREATE TABLE ESOCIAL_S5002 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VLR_BASE_IRRF DECIMAL(18,2) NOT NULL DEFAULT 0,
    VLR_IRRF      DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5003')
CREATE TABLE ESOCIAL_S5003 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    CPF           VARCHAR(20)   NOT NULL,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_FGTS       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ESOCIAL_S5011')
CREATE TABLE ESOCIAL_S5011 (
    ID            INT IDENTITY(1,1) PRIMARY KEY,
    EMPRESA       VARCHAR(100)  NOT NULL,
    COMPETENCIA   VARCHAR(10)   NOT NULL,
    VR_CP_APUR    DECIMAL(18,2) NOT NULL DEFAULT 0,
    VR_IRRF       DECIMAL(18,2) NOT NULL DEFAULT 0,
    ARQUIVO       VARCHAR(260)  NOT NULL
);
GO

PRINT 'folha_beatriz: OK';
GO

SELECT name AS tabela_criada FROM sys.tables WHERE name LIKE 'ESOCIAL%' ORDER BY name;
GO
